### ISSUE TITLE
1.20.1?

### ISSUE THREAD

**Issue by roboboredom** [JayZX535/alexs-tamables-mc#1]
I would normally never beg for an update because its toxic behavior, but this is freaking adorable and I wish it was on 1.20.1 so I can add it to the latest alex's mobs + alex's caves :3

**Comment by JayZX535** [comment]
Glad to hear you're enjoying the mod, however as noted in the FAQs on the Curseforge and Modrinth pages, I have no intention of updating it past 1.18.  Sorry!

**Comment by roboboredom** [comment]
Ah dang, well thanks for the 1.18 version!
________________________________

**Comment by vinnyg0621** [comment]
why, please tell me! 😕

**Comment by JayZX535** [comment]
I work on these mods in my free time and 1.18 (and somewhat 1.16) is where my other active projects are.
